"""
Problem 973: Lucky Number Sieve

Compute the sum of all lucky numbers below 10^5.

Lucky numbers are generated by a sieve process:
    1. Start with odd numbers: 1, 3, 5, 7, 9, 11, 13, ...
    2. The second number is 3, so remove every 3rd element.
    3. The next surviving number is 7, so remove every 7th element.
    4. Repeat with each subsequent surviving number.

Key results:
    - Lucky numbers share many properties with primes (Goldbach-like conjectures)
    - Their density is asymptotically ~ n / ln(n), similar to primes
    - answer = sum of all lucky numbers < 10^5

Methods:
    1. lucky_sieve          — generate lucky numbers via iterative sieving
    2. lucky_counting_func  — count lucky numbers up to x (pi_L analog)
    3. gap_analysis         — compute gaps between consecutive lucky numbers
    4. lucky_vs_prime_density — compare lucky and prime counting functions
"""

from math import isqrt
from collections import Counter

def lucky_sieve(N):
    """Return list of all lucky numbers below N."""
    nums = list(range(1, N, 2))  # start with odd numbers
    idx = 1
    while idx < len(nums) and nums[idx] <= len(nums):
        step = nums[idx]
        nums = [nums[i] for i in range(len(nums)) if (i + 1) % step != 0]
        idx += 1
    return nums

def lucky_counting_func(luckys, checkpoints):
    """For each x in checkpoints, count lucky numbers <= x."""
    counts = []
    j = 0
    for x in sorted(checkpoints):
        while j < len(luckys) and luckys[j] <= x:
            j += 1
        counts.append(j)
    return counts

def gap_analysis(luckys):
    """Return list of gaps and a Counter of gap frequencies."""
    gaps = [luckys[i + 1] - luckys[i] for i in range(len(luckys) - 1)]
    return gaps, Counter(gaps)

def prime_sieve(n):
    """Return list of primes up to n."""
    s = bytearray(b'\x01') * (n + 1)
    s[0] = s[1] = 0
    for i in range(2, isqrt(n) + 1):
        if s[i]:
            s[i * i :: i] = bytearray(len(s[i * i :: i]))
    return [i for i in range(2, n + 1) if s[i]]

#  Verification
# Known first lucky numbers: 1, 3, 7, 9, 13, 15, 21, 25, 31, 33, 37, 39, 43, 49
_luckys = lucky_sieve(50)
assert _luckys == [1, 3, 7, 9, 13, 15, 21, 25, 31, 33, 37, 39, 43, 49], \
    f"Lucky sieve mismatch: {_luckys}"

#  Main computation
N = 10 ** 5
luckys = lucky_sieve(N)
answer = sum(luckys)
print(answer)

#  Visualization — 4-panel figure
