"""
Problem 149: Searching for a Maximum-sum Subsequence

Find the greatest sum of any contiguous subsequence in any direction
(horizontal, vertical, diagonal, anti-diagonal) in a 2000x2000 table
generated by a lagged Fibonacci generator.
"""

def solve():
    N = 2000
    SZ = N * N

    # Generate the lagged Fibonacci sequence (1-indexed)
    s = [0] * (SZ + 1)
    for k in range(1, 56):
        s[k] = (100003 - 200003 * k + 300007 * k * k * k) % 1000000 - 500000
    for k in range(56, SZ + 1):
        s[k] = (s[k - 24] + s[k - 55] + 1000000) % 1000000 - 500000

    # Build 2000x2000 table (0-indexed)
    table = []
    for i in range(N):
        row = []
        for j in range(N):
            row.append(s[N * i + j + 1])
        table.append(row)

    # Kadane's algorithm
    def kadane(seq):
        max_here = 0
        max_so_far = float('-inf')
        for x in seq:
            max_here = max(x, max_here + x)
            max_so_far = max(max_so_far, max_here)
        return max_so_far

    ans = float('-inf')

    # Horizontal
    for i in range(N):
        ans = max(ans, kadane(table[i]))

    # Vertical
    for j in range(N):
        col = [table[i][j] for i in range(N)]
        ans = max(ans, kadane(col))

    # Diagonal (top-left to bottom-right)
    for d in range(-(N - 1), N):
        diag = []
        for i in range(max(0, -d), N):
            j = i + d
            if j < 0 or j >= N:
                continue
            diag.append(table[i][j])
        if diag:
            ans = max(ans, kadane(diag))

    # Anti-diagonal (top-right to bottom-left)
    for d in range(0, 2 * N - 1):
        adiag = []
        for i in range(max(0, d - N + 1), min(N, d + 1)):
            j = d - i
            if 0 <= j < N:
                adiag.append(table[i][j])
        if adiag:
            ans = max(ans, kadane(adiag))

    print(ans)

if __name__ == "__main__":
    solve()
