"""
Problem 165: Intersections

Count distinct interior intersection points of 5000 line segments
generated by the Blum Blum Shub pseudo-random number generator.
Uses exact rational arithmetic to identify distinct points.
"""

from math import gcd

def solve():
    N = 5000

    # Generate segments using BBS
    s = 290797
    coords = []
    for _ in range(4 * N):
        s = s * s % 50515093
        coords.append(s % 500)

    segments = []
    for i in range(N):
        x1, y1, x2, y2 = coords[4*i], coords[4*i+1], coords[4*i+2], coords[4*i+3]
        segments.append((x1, y1, x2, y2))

    points = set()

    for i in range(N):
        x1, y1, x2, y2 = segments[i]
        dx1, dy1 = x2 - x1, y2 - y1
        for j in range(i + 1, N):
            x3, y3, x4, y4 = segments[j]
            dx2, dy2 = x4 - x3, y4 - y3

            D = dx1 * dy2 - dy1 * dx2
            if D == 0:
                continue

            t_num = (x3 - x1) * dy2 - (y3 - y1) * dx2
            u_num = (x3 - x1) * dy1 - (y3 - y1) * dx1

            # Interior: 0 < t < 1 and 0 < u < 1
            if D > 0:
                if not (0 < t_num < D and 0 < u_num < D):
                    continue
            else:
                if not (D < t_num < 0 and D < u_num < 0):
                    continue

            # Intersection: (x1 + t_num/D * dx1, y1 + t_num/D * dy1)
            # = (x1*D + t_num*dx1, y1*D + t_num*dy1) / D
            px = x1 * D + t_num * dx1
            py = y1 * D + t_num * dy1
            dd = D

            if dd < 0:
                px, py, dd = -px, -py, -dd

            g = gcd(gcd(abs(px), abs(py)), dd)
            px //= g
            py //= g
            dd //= g

            points.add((px, py, dd))

    print(len(points))

solve()
