#include <bits/stdc++.h>
using namespace std;

// Problem 165: Intersections
// Find distinct interior intersection points of 5000 line segments
// generated by the Blum Blum Shub generator.

typedef long long ll;
typedef __int128 lll;

struct Seg {
    ll x1, y1, x2, y2;
};

int main() {
    // Generate segments
    const int N = 5000;
    vector<Seg> segs(N);

    ll s = 290797;
    auto next_s = [&]() -> ll {
        s = (ll)((lll)s * s % 50515093LL);
        return s;
    };

    for (int i = 0; i < N; i++) {
        ll t1 = next_s() % 500;
        ll t2 = next_s() % 500;
        ll t3 = next_s() % 500;
        ll t4 = next_s() % 500;
        segs[i] = {t1, t2, t3, t4};
    }

    // For each pair, find interior intersection
    // Use exact rational arithmetic
    // Store points as (px/d, py/d) reduced to lowest terms with d > 0

    set<tuple<ll,ll,ll,ll>> points;

    auto gcd_func = [](ll a, ll b) -> ll {
        a = abs(a); b = abs(b);
        while (b) { a %= b; swap(a, b); }
        return a;
    };

    for (int i = 0; i < N; i++) {
        ll x1 = segs[i].x1, y1 = segs[i].y1;
        ll x2 = segs[i].x2, y2 = segs[i].y2;
        ll dx1 = x2 - x1, dy1 = y2 - y1;

        for (int j = i + 1; j < N; j++) {
            ll x3 = segs[j].x1, y3 = segs[j].y1;
            ll x4 = segs[j].x2, y4 = segs[j].y2;
            ll dx2 = x4 - x3, dy2 = y4 - y3;

            // D = dx1 * dy2 - dy1 * dx2
            ll D = dx1 * dy2 - dy1 * dx2;
            if (D == 0) continue; // parallel or collinear

            // t_num = (x3 - x1) * dy2 - (y3 - y1) * dx2
            // u_num = (x3 - x1) * dy1 - (y3 - y1) * dx1
            ll t_num = (x3 - x1) * dy2 - (y3 - y1) * dx2;
            ll u_num = (x3 - x1) * dy1 - (y3 - y1) * dx1;

            // Interior: 0 < t < 1 and 0 < u < 1
            // t = t_num / D, u = u_num / D
            // If D > 0: 0 < t_num < D and 0 < u_num < D
            // If D < 0: D < t_num < 0 and D < u_num < 0

            bool t_ok, u_ok;
            if (D > 0) {
                t_ok = (t_num > 0 && t_num < D);
                u_ok = (u_num > 0 && u_num < D);
            } else {
                t_ok = (t_num < 0 && t_num > D);
                u_ok = (u_num < 0 && u_num > D);
            }

            if (!t_ok || !u_ok) continue;

            // Compute intersection point: (x1 + t * dx1, y1 + t * dy1)
            // = (x1 + t_num * dx1 / D, y1 + t_num * dy1 / D)
            // = ((x1 * D + t_num * dx1) / D, (y1 * D + t_num * dy1) / D)

            lll px = (lll)x1 * D + (lll)t_num * dx1;
            lll py = (lll)y1 * D + (lll)t_num * dy1;
            lll dd = D;

            // Normalize: dd > 0
            if (dd < 0) { px = -px; py = -py; dd = -dd; }

            // Reduce to lowest terms
            ll px_l = (ll)px, py_l = (ll)py, dd_l = (ll)dd;
            ll g = gcd_func(gcd_func(abs(px_l), abs(py_l)), dd_l);
            px_l /= g; py_l /= g; dd_l /= g;

            points.insert({px_l, py_l, dd_l, 0});
        }
    }

    cout << points.size() << endl;
    return 0;
}
